"""SQL-safety **policy** for the first-party kernel — the allowlist, as data.

This module is the single auditable surface of MCPg's SQL-safety decision:
which statement types, ``pglast`` AST node types, functions, and extensions
an agent-supplied query may contain. The *mechanism* that walks a parsed
query against this policy lives in :mod:`mcpg.sql.safety`; keeping the two
apart means the walker cannot silently widen what's permitted, and this
table can be reviewed on its own (see the de-vendor plan's security-review
gate).

Re-authored verbatim from the formerly-vendored ``crystaldba/postgres-mcp``
``safe_sql.py`` (MIT); the permitted sets are pinned identical by the
adversarial suite + the differential parity test.
"""

from __future__ import annotations

import re

from pglast.ast import (
    A_ArrayExpr,
    A_Const,
    A_Expr,
    A_Indices,
    A_Indirection,
    A_Star,
    Alias,
    BitString,
    Boolean,
    BooleanTest,
    BoolExpr,
    CaseExpr,
    CaseWhen,
    ClosePortalStmt,
    CoalesceExpr,
    CollateClause,
    ColumnRef,
    CommonTableExpr,
    CreateExtensionStmt,
    DeallocateStmt,
    DeclareCursorStmt,
    DefElem,
    ExplainStmt,
    FetchStmt,
    Float,
    FromExpr,
    FuncCall,
    GroupingFunc,
    GroupingSet,
    Integer,
    JoinExpr,
    MinMaxExpr,
    NamedArgExpr,
    NotifyStmt,
    NullTest,
    ParamRef,
    PrepareStmt,
    RangeFunction,
    RangeSubselect,
    RangeTableFunc,
    RangeTableFuncCol,
    RangeTableSample,
    RangeVar,
    RawStmt,
    ResTarget,
    RowCompareExpr,
    RowExpr,
    ScalarArrayOpExpr,
    SelectStmt,
    SortBy,
    SortGroupClause,
    SQLValueFunction,
    String,
    SubLink,
    TableFunc,
    TableSampleClause,
    TargetEntry,
    TypeCast,
    TypeName,
    VacuumStmt,
    VariableShowStmt,
    WindowClause,
    WindowDef,
    WindowFunc,
    WithClause,
)

PG_CATALOG_PATTERN = re.compile(r"^pg_catalog\.(.+)$")
# Pattern to validate LIKE expressions - must either start with % or end with %, but not both
LIKE_PATTERN = re.compile(r"^[^%]+%$")

ALLOWED_STMT_TYPES: set[type] = {
    SelectStmt,  # Regular SELECT
    ExplainStmt,  # EXPLAIN SELECT
    CreateExtensionStmt,  # CREATE EXTENSION
    VariableShowStmt,  # SHOW statements
    VacuumStmt,  # VACUUM and ANALYZE statements
    PrepareStmt,  # PREPARE statement (for prepared queries)
    # ExecuteStmt,  # EXECUTE statement (for prepared queries)
    DeallocateStmt,  # DEALLOCATE statement (for prepared queries)
    # CopyStmt,  # COPY TO (for exporting query results - will be validated to ensure COPY FROM is not allowed)
    # DiscardStmt,  # DISCARD (for discarding client-side caches)
    DeclareCursorStmt,  # DECLARE CURSOR (for cursor operations)
    ClosePortalStmt,  # CLOSE (for closing cursors)
    FetchStmt,  # FETCH (for retrieving cursor results)
    # CheckPointStmt,  # CHECKPOINT (read-only administrative command)
    # ListenStmt,  # LISTEN (notification system)
    # UnlistenStmt,  # UNLISTEN (notification system)
    # VariableSetStmt,  # SET (for session variables - will be validated)
}

ALLOWED_FUNCTIONS: set[str] = {
    # Aggregate functions
    "array_agg",
    "avg",
    "bit_and",
    "bit_or",
    "bool_and",
    "bool_or",
    "count",
    "every",
    "json_agg",
    "jsonb_agg",
    "json_object_agg",
    "jsonb_object_agg",
    "max",
    "min",
    "string_agg",
    "sum",
    "xmlagg",
    # Mathematical functions
    "abs",
    "cbrt",
    "ceil",
    "ceiling",
    "degrees",
    "div",
    "erf",
    "erfc",
    "exp",
    "factorial",
    "floor",
    "gcd",
    "lcm",
    "ln",
    "log",
    "log10",
    "min_scale",
    "mod",
    "pi",
    "power",
    "radians",
    "random",
    "random_normal",
    "round",
    "scale",
    "setseed",
    "sign",
    "sqrt",
    "trim_scale",
    "trunc",
    "width_bucket",
    "percentile_cont",
    "percentile_disc",
    "mode",
    # Trigonometric functions
    "acos",
    "acosd",
    "asin",
    "asind",
    "atan",
    "atand",
    "atan2",
    "atan2d",
    "cos",
    "cosd",
    "cot",
    "cotd",
    "sin",
    "sind",
    "tan",
    "tand",
    # Hyperbolic functions
    "sinh",
    "cosh",
    "tanh",
    "asinh",
    "acosh",
    "atanh",
    # Array functions and operators
    "array",
    "array_append",
    "array_cat",
    "array_dims",
    "array_fill",
    "array_length",
    "array_lower",
    "array_ndims",
    "array_position",
    "array_positions",
    "array_prepend",
    "array_remove",
    "array_replace",
    "array_sample",
    "array_shuffle",
    "array_to_string",
    "array_upper",
    "cardinality",
    "string_to_array",
    "trim_array",
    "unnest",
    "any",
    # String functions
    "ascii",
    "bit_length",
    "btrim",
    "char_length",
    "character_length",
    "chr",
    "concat",
    "concat_ws",
    "convert",
    "convert_from",
    "convert_to",
    "decode",
    "encode",
    "format",
    "initcap",
    "left",
    "length",
    "lower",
    "lpad",
    "ltrim",
    "md5",
    "normalize",
    "octet_length",
    "overlay",
    "parse_ident",
    "position",
    "quote_ident",
    "quote_literal",
    "quote_nullable",
    "repeat",
    "replace",
    "reverse",
    "right",
    "rpad",
    "rtrim",
    "split_part",
    "starts_with",
    "string_to_table",
    "strpos",
    "substr",
    "substring",
    "to_ascii",
    "to_bin",
    "to_hex",
    "to_oct",
    "translate",
    "trim",
    "upper",
    "unistr",
    "unicode_assigned",
    # Pattern matching functions
    "regexp_match",
    "regexp_matches",
    "regexp_replace",
    "regexp_split_to_array",
    "regexp_split_to_table",
    "regexp_substr",
    "regexp_count",
    "regexp_instr",
    "regexp_like",
    # Type casting functions
    "regclass",
    "to_char",
    "to_date",
    "to_number",
    "to_timestamp",
    # Information functions
    "current_catalog",
    "current_database",
    "current_query",
    "current_role",
    "current_schema",
    "current_schemas",
    "current_setting",
    "current_user",
    "pg_backend_pid",
    "pg_blocking_pids",
    "pg_conf_load_time",
    "pg_current_logfile",
    "pg_jit_available",
    "pg_safe_snapshot_blocking_pids",
    "pg_trigger_depth",
    "session_user",
    "system_user",
    "user",
    "version",
    "unicode_version",
    "icu_unicode_version",
    # Database object information functions
    "pg_column_size",
    "pg_column_compression",
    "pg_column_toast_chunk_id",
    "pg_database_size",
    "pg_indexes_size",
    "pg_get_indexdef",
    "pg_relation_filenode",
    "pg_relation_size",
    "pg_size_bytes",
    "pg_size_pretty",
    "pg_table_size",
    "pg_tablespace_size",
    "pg_total_relation_size",
    # Security privilege check functions
    "has_any_column_privilege",
    "has_column_privilege",
    "has_database_privilege",
    "has_foreign_data_wrapper_privilege",
    "has_function_privilege",
    "has_language_privilege",
    "has_parameter_privilege",
    "has_schema_privilege",
    "has_sequence_privilege",
    "has_server_privilege",
    "has_table_privilege",
    "has_tablespace_privilege",
    "has_type_privilege",
    "pg_has_role",
    "row_security_active",
    # JSON functions
    "json",
    "json_array_length",
    "jsonb_array_length",
    "json_each",
    "jsonb_each",
    "json_each_text",
    "jsonb_each_text",
    "json_extract_path",
    "jsonb_extract_path",
    "json_extract_path_text",
    "jsonb_extract_path_text",
    "json_object_keys",
    "jsonb_object_keys",
    "json_array_elements",
    "jsonb_array_elements",
    "json_array_elements_text",
    "jsonb_array_elements_text",
    "json_typeof",
    "jsonb_typeof",
    "json_strip_nulls",
    "jsonb_strip_nulls",
    "jsonb_set",
    "jsonb_set_path",
    "jsonb_set_lax",
    "jsonb_pretty",
    "json_build_array",
    "jsonb_build_array",
    "json_build_object",
    "jsonb_build_object",
    "json_object",
    "jsonb_object",
    "json_scalar",
    "json_serialize",
    "json_populate_record",
    "jsonb_populate_record",
    "jsonb_populate_record_valid",
    "json_populate_recordset",
    "jsonb_populate_recordset",
    "json_to_record",
    "jsonb_to_record",
    "json_to_recordset",
    "jsonb_to_recordset",
    "jsonb_insert",
    "jsonb_path_exists",
    "jsonb_path_match",
    "jsonb_path_query",
    "jsonb_path_query_array",
    "jsonb_path_query_first",
    "jsonb_path_exists_tz",
    "jsonb_path_match_tz",
    "jsonb_path_query_tz",
    "jsonb_path_query_array_tz",
    "jsonb_path_query_first_tz",
    "jsonbv_typeof",
    "to_json",
    "to_jsonb",
    "array_to_json",
    "row_to_json",
    # Object Info
    "pg_get_expr",
    "pg_get_functiondef",
    "pg_get_function_arguments",
    "pg_get_function_identity_arguments",
    "pg_get_function_result",
    "pg_get_catalog_foreign_keys",
    "pg_get_constraintdef",
    "pg_get_userbyid",
    "pg_get_keywords",
    "pg_get_partkeydef",
    # Encoding Functions
    "pg_basetype",
    "pg_client_encoding",
    "pg_encoding_to_char",
    "pg_char_to_encoding",
    # Validity Checking
    "pg_input_is_valid",
    "pg_input_error_info",
    # Object Definition/Information Functions
    "pg_get_serial_sequence",
    "pg_get_viewdef",
    "pg_get_ruledef",
    "pg_get_triggerdef",
    "pg_get_statisticsobjdef",
    # Type Information and Conversion
    "pg_typeof",
    "format_type",
    "to_regtype",
    "to_regtypemod",
    # Object Name/OID Translation
    "to_regclass",
    "to_regcollation",
    "to_regnamespace",
    "to_regoper",
    "to_regoperator",
    "to_regproc",
    "to_regprocedure",
    "to_regrole",
    # Index Property Functions
    "pg_index_column_has_property",
    "pg_index_has_property",
    "pg_indexam_has_property",
    # Schema Visibility Functions
    "pg_collation_is_visible",
    "pg_conversion_is_visible",
    "pg_function_is_visible",
    "pg_opclass_is_visible",
    "pg_operator_is_visible",
    "pg_opfamily_is_visible",
    "pg_statistics_obj_is_visible",
    "pg_table_is_visible",
    "pg_ts_config_is_visible",
    "pg_ts_dict_is_visible",
    "pg_ts_parser_is_visible",
    "pg_ts_template_is_visible",
    "pg_type_is_visible",
    # Date/Time Functions
    "age",  # When used with timestamp arguments (not transaction IDs)
    "clock_timestamp",
    "current_date",
    "current_time",
    "current_timestamp",
    "date_part",
    "date_trunc",
    "extract",
    "isfinite",
    "justify_days",
    "justify_hours",
    "justify_interval",
    "localtime",
    "localtimestamp",
    "make_date",
    "make_interval",
    "make_time",
    "make_timestamp",
    "make_timestamptz",
    "now",
    "statement_timestamp",
    "timeofday",
    "transaction_timestamp",
    # Additional Type Conversion
    "cast",
    "text",
    "bool",
    "int2",
    "int4",
    "int8",
    "float4",
    "float8",
    "numeric",
    "date",
    "time",
    "timetz",
    "timestamp",
    "timestamptz",
    "interval",
    # ACL functions
    "acldefault",
    "aclexplode",
    "makeaclitem",
    # System/Configuration Information
    "pg_tablespace_location",  # Exposes filesystem paths
    "pg_tablespace_databases",  # Exposes system-wide information
    "pg_settings_get_flags",  # Exposes configuration details
    "pg_options_to_table",  # Exposes internal storage options
    # Transaction/WAL Information
    "pg_current_xact_id",  # Exposes transaction details
    "pg_current_snapshot",  # Exposes transaction snapshots
    "pg_snapshot_xip",  # Exposes in-progress transactions
    "pg_xact_commit_timestamp",  # Transaction timestamp details
    # Control Data Functions
    "pg_control_checkpoint",  # Internal checkpoint state
    "pg_control_system",  # Control file state
    "pg_control_init",  # Cluster initialization state
    "pg_control_recovery",  # Recovery state
    # WAL Functions
    "pg_available_wal_summaries",  # WAL summary information
    "pg_wal_summary_contents",  # WAL contents
    "pg_get_wal_summarizer_state",  # WAL summarizer state
    # Network Information
    "inet_client_addr",  # Client network details
    "inet_client_port",  # Client port information
    "inet_server_addr",  # Server network details
    "inet_server_port",  # Server port information
    # Temporary Schema Information
    "pg_my_temp_schema",  # Exposes temp schema OIDs
    "pg_is_other_temp_schema",  # Shows other sessions' temp schemas
    # Notification/Channel Information
    "pg_listening_channels",  # Shows active notification channels
    "pg_notification_queue_usage",  # Exposes notification queue state
    # Server State Information
    "pg_postmaster_start_time",  # Shows server start time
    # Recovery Information Functions (safe ones)
    "pg_is_in_recovery",
    # Hypopg functions
    "hypopg_create_index",
    "hypopg_reset",
    "hypopg_relation_size",
    "hypopg_list_indexes",
    "hypopg_get_indexdef",
    "hypopg_hide_index",
    "hypopg_unhide_index",
    # XML Functions (read-only)
    "xml",
    "xmlcomment",
    "xmlconcat",
    "xmlelement",
    "xmlforest",
    "xmlpi",
    "xmlroot",
    "xmlexists",
    "xml_is_well_formed",
    "xml_is_well_formed_document",
    "xml_is_well_formed_content",
    "xpath",
    "xpath_exists",
    "xmltable",
    "xmlnamespaces",
    # Network/IP Address Functions
    "abbrev",
    "broadcast",
    "cidr_split",
    "family",
    "host",
    "hostmask",
    "inet_merge",
    "inet_same_family",
    "macaddr8_set7bit",
    "masklen",
    "netmask",
    "network",
    "set_bit",
    "set_masklen",
    # Full-Text Search Functions
    "array_to_tsvector",
    "get_current_ts_config",
    "numnode",
    "plainto_tsquery",
    "phraseto_tsquery",
    "querytree",
    "setweight",
    "strip",
    "to_tsquery",
    "to_tsvector",
    "ts_debug",
    "ts_delete",
    "ts_filter",
    "ts_headline",
    "ts_lexize",
    "ts_parse",
    "ts_rank",
    "ts_rank_cd",
    "ts_rewrite",
    "ts_stat",
    "ts_token_type",
    "tsvector_to_array",
    "websearch_to_tsquery",
    # Range Functions
    "isempty",
    "lower_inc",
    "upper_inc",
    "lower_inf",
    "upper_inf",
    "range_merge",
    # Geometry Functions
    "area",
    "center",
    "diameter",
    "height",
    "isclosed",
    "isopen",
    "npoints",
    "pclose",
    "popen",
    "radius",
    "width",
    # UUID Functions
    "gen_random_uuid",
    # Enum Functions
    "enum_first",
    "enum_last",
    "enum_range",
    # Sequence Functions (read-only)
    "currval",
    "lastval",
    # pg_trgm Functions
    "similarity",
    "show_trgm",
    "show_limit",
    "word_similarity",
    "strict_word_similarity",
    # pg_crypto Functions (read-only)
    "digest",
    "hmac",
    "encrypt",
    "gen_salt",
    "crypt",
    # earthdistance/cube Functions
    "earth_distance",
    "earth_box",
    "ll_to_earth",
    "earth_to_ll",
    "cube_distance",
    # fuzzystrmatch Functions
    "soundex",
    "difference",
    "levenshtein",
    "metaphone",
    "dmetaphone",
    # Window functions
    "row_number",
    "rank",
    "dense_rank",
    "percent_rank",
    "cume_dist",
    "ntile",
    "lag",
    "lead",
    "first_value",
    "last_value",
    "nth_value",
}

ALLOWED_NODE_TYPES: set[type] = ALLOWED_STMT_TYPES | {
    # Basic SELECT components
    ResTarget,
    ColumnRef,
    A_Star,
    A_Const,
    A_Expr,
    BoolExpr,
    BooleanTest,
    NullTest,
    RangeVar,
    JoinExpr,
    FromExpr,
    WithClause,
    CommonTableExpr,
    # Basic operators
    A_Expr,
    BoolExpr,
    SubLink,
    MinMaxExpr,
    RowExpr,
    # EXPLAIN components
    ExplainStmt,
    DefElem,
    # SHOW components
    VariableShowStmt,
    # VACUUM and ANALYZE components
    VacuumStmt,
    # Sorting/grouping
    SortBy,
    SortGroupClause,
    # Constants and basic types
    Integer,
    Float,
    String,
    BitString,
    Boolean,
    RawStmt,
    ParamRef,
    SQLValueFunction,
    # Function calls and type casting
    FuncCall,
    TypeCast,
    DefElem,
    TypeName,
    Alias,
    CaseExpr,
    CaseWhen,
    RangeSubselect,
    CoalesceExpr,
    NamedArgExpr,
    RangeFunction,
    A_ArrayExpr,
    # Window functions
    WindowFunc,
    WindowDef,
    WindowClause,
    # Table functions
    TableFunc,
    RangeTableFunc,
    RangeTableFuncCol,
    # Array access
    A_Indirection,
    A_Indices,
    # GROUPING SETS, CUBE, ROLLUP
    GroupingSet,
    GroupingFunc,
    # Table sampling
    RangeTableSample,
    TableSampleClause,
    # Row comparison
    RowCompareExpr,
    # Collation
    CollateClause,
    # Others
    TargetEntry,
    # Additional expression types
    ScalarArrayOpExpr,  # ARRAY[...] @> or <@ operators
    NotifyStmt,  # NOTIFY command
}

ALLOWED_EXTENSIONS: set[str] = {
    # Core PostgreSQL extensions
    "hypopg",
    "pg_stat_statements",
    "pg_trgm",
    "btree_gin",
    "btree_gist",
    "earthdistance",
    "cube",
    "fuzzystrmatch",
    "intarray",
    "pgcrypto",
    "hstore",
    "ltree",
    "xml2",
    "tablefunc",
    "tsm_system_rows",
    "tsm_system_time",
    "unaccent",
    "uuid-ossp",
    # Common extensions
    "adminpack",
    "amcheck",
    "bloom",
    "citext",
    "dict_int",
    "dict_xsyn",
    "file_fdw",
    "intagg",
    "isn",
    "lo",
    "pg_buffercache",
    "pg_freespacemap",
    "pg_prewarm",
    "pg_visibility",
    "pgrowlocks",
    "pgstattuple",
    "plpgsql",
    "seg",
    "spi",
    "sslinfo",
    # Foreign data wrappers
    "postgres_fdw",
    "dblink",
    "mysql_fdw",
    "mongo_fdw",
    "tds_fdw",
    "oracle_fdw",
    # Popular extensions
    "postgis",
    "pgrouting",
    "timescaledb",
    "pg_partman",
    "orafce",
    "pgaudit",
    "pgtap",
    "pgsphere",
    "pg_qualstats",
    "pg_hint_plan",
    "auto_explain",
    "pg_wait_sampling",
    "plv8",
    "pg_stat_monitor",
    "pg_cron",
    "pglogical",
    "pgq",
    "pgpool_adm",
    "pg_fuzzystrmatch",
    "pg_bigm",
    "pgvector",
    "rum",
    "zhparser",
    "ip4r",
    "chkpass",
    "tsvector2",
    "pg_stat_kcache",
    "wal2json",
    "pg_repack",
    # Programming languages
    "plperl",
    "plperlu",
    "plpython3u",
    "plpython",
    "pltcl",
    "pltclu",
    "pljava",
    "plrust",
    # AWS RDS extensions
    "aws_commons",
    "aws_s3",
    # Supabase extensions
    "h3",
    "pg_graphql",
    "pg_net",
    "pgjwt",
    "moddatetime",
    # Additional data types
    "age",
    "semver",
    "rdkit",
    "vector",
    # Distributed PostgreSQL
    "citus",
    # Other validated extensions
    "pg_tle",
    "pg_roaringbitmap",
    "pg_ivm",
    "pg_rational",
    "pg_partman_bgw",
    "q3c",
    "pg_track_settings",
    "pg_variables",
    "pg_walinspect",
    "pgmq",
    "address_standardizer",
    "address_standardizer_data_us",
    "postgis_raster",
    "postgis_sfcgal",
    "postgis_tiger_geocoder",
    "postgis_topology",
}
