"""Doc-table drift guard.

Two reference catalogues in the docs used to rot every time a tool or
module was added:

* the **tool index** in ``docs/tools.md`` — before this guard it had
  drifted ~90 tools out of date and listed 3 that no longer existed;
* the **module map** in ``docs/architecture.md`` — ~35 modules were
  undocumented and a handful were named wrong.

Both are now generated by ``tools/generate_doc_tables.py`` from the
single sources of truth (the registered tool surface and the package
layout). This test asserts the docs still match what the generator
produces, so a new tool or module can't silently go undocumented and a
removed one can't linger.

When you add a tool or a module, regenerate and paste the block between
the ``<!-- BEGIN generated: … -->`` / ``<!-- END generated: … -->``
markers::

    python tools/generate_doc_tables.py --tools     # → docs/tools.md
    python tools/generate_doc_tables.py --modules    # → docs/architecture.md
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path
from types import ModuleType

import pytest

_REPO = Path(__file__).resolve().parents[2]
_TOOLS_MD = _REPO / "docs" / "tools.md"
_ARCH_MD = _REPO / "docs" / "architecture.md"


def _load_generator() -> ModuleType:
    path = _REPO / "tools" / "generate_doc_tables.py"
    spec = importlib.util.spec_from_file_location("generate_doc_tables", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _marked_region(text: str, kind: str) -> str:
    """Return the text between the BEGIN/END markers for a generated block."""
    m = re.search(
        rf"<!-- BEGIN generated: {re.escape(kind)}.*?-->\n(.*?)\n<!-- END generated: {re.escape(kind)} -->",
        text,
        re.S,
    )
    assert m, f"missing generated markers for {kind!r}"
    return m.group(1)


def _tool_names_in_index() -> set[str]:
    """Tool names from the last (``Tools``) column of the index table."""
    region = _marked_region(_TOOLS_MD.read_text(encoding="utf-8"), "tool-index")
    names: set[str] = set()
    for line in region.splitlines():
        if not line.startswith("| **"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        # cells = [category, gate, tools]; only the tools cell is authoritative.
        names.update(re.findall(r"`([a-z][a-z0-9_]+)`", cells[-1]))
    return names


def _module_names_in_map() -> set[str]:
    """Module names from the first column of the module-map table."""
    region = _marked_region(_ARCH_MD.read_text(encoding="utf-8"), "module-map")
    return set(re.findall(r"^\| `(mcpg\.[a-z0-9_.]+)` \|", region, re.M))


def test_tools_md_index_matches_registered_surface() -> None:
    gen = _load_generator()
    expected = gen._snapshot_names()
    documented = _tool_names_in_index()
    missing = sorted(expected - documented)
    phantom = sorted(documented - expected)
    if missing or phantom:
        pytest.fail(
            "docs/tools.md tool index drifted from the registered surface.\n"
            f"  missing ({len(missing)}): {', '.join(missing) or '—'}\n"
            f"  phantom ({len(phantom)}): {', '.join(phantom) or '—'}\n"
            "Regenerate: python tools/generate_doc_tables.py --tools "
            "(paste between the tool-index markers)."
        )


def test_architecture_module_map_matches_package() -> None:
    gen = _load_generator()
    expected = gen.documented_module_names()
    documented = _module_names_in_map()
    missing = sorted(expected - documented)
    phantom = sorted(documented - expected)
    if missing or phantom:
        pytest.fail(
            "docs/architecture.md module map drifted from src/mcpg.\n"
            f"  missing ({len(missing)}): {', '.join(missing) or '—'}\n"
            f"  phantom ({len(phantom)}): {', '.join(phantom) or '—'}\n"
            "Regenerate: python tools/generate_doc_tables.py --modules "
            "(paste between the module-map markers)."
        )


def test_generated_tables_are_internally_consistent() -> None:
    """The generator's own tool rows cover the snapshot exactly."""
    gen = _load_generator()
    emitted = [n for _, names, _ in gen.tool_index_rows() for n in names]
    assert len(emitted) == len(set(emitted)), "generator emitted a duplicate tool"
    assert set(emitted) == gen._snapshot_names(), "generator tool rows != snapshot"
