"""Server-side cursor manager — pageable reads of large result sets.

PostgreSQL's ``DECLARE ... CURSOR`` keeps a result set on the server
side and lets the client ``FETCH`` it in batches. That's the natural
mechanism for paging through millions of rows without the round-trip
or memory cost of pulling them all at once.

Cursors are bound to a transaction (or a session, for ``WITH HOLD``).
To bridge that to the stateless MCP tool model we hold a *dedicated*
psycopg connection per open cursor — separate from the main pool so
opening N long-lived cursors doesn't starve other tools. Each cursor
has a TTL (default 5 minutes of idleness); the manager sweeps
expired cursors lazily, at the start of every call.

A hard cap on concurrent cursors prevents unbounded resource use.
"""

from __future__ import annotations

import asyncio
import logging
import secrets
import time
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Any

import psycopg
from psycopg.rows import dict_row

from mcpg.sql import SafeSqlDriver, SqlDriver

logger = logging.getLogger(__name__)

DEFAULT_CURSOR_TTL_SECONDS = 300.0
DEFAULT_MAX_OPEN_CURSORS = 16
DEFAULT_FETCH_BATCH = 100
HARD_FETCH_BATCH = 10_000


class CursorError(Exception):
    """Raised when a cursor operation fails or is rejected."""


@dataclass(slots=True)
class _ActiveCursor:
    cursor_id: str
    sql: str
    connection: psycopg.AsyncConnection[Any]
    last_touched: float = field(default_factory=time.monotonic)
    rows_returned: int = 0
    closed: bool = False
    # psycopg's AsyncConnection is NOT safe for concurrent use by
    # multiple tasks. A per-cursor lock serialises every database
    # operation on the held connection so a racing fetch + close (or
    # two fetches on the same cursor_id) can't corrupt the protocol.
    use_lock: asyncio.Lock = field(default_factory=asyncio.Lock)


@dataclass(frozen=True, slots=True)
class CursorInfo:
    """Public-facing description of one open cursor."""

    cursor_id: str
    sql: str
    rows_returned: int
    age_seconds: float
    ttl_seconds: float


@dataclass(frozen=True, slots=True)
class FetchResult:
    """Result of a single :meth:`CursorManager.fetch` call.

    ``exhausted`` is ``True`` when the FETCH returned fewer rows than
    requested — the agent can stop polling at that point. The cursor
    is not automatically closed; callers should call ``close_cursor``
    when done (or let the TTL sweep it).
    """

    cursor_id: str
    columns: list[str]
    rows: list[dict[str, Any]]
    row_count: int
    exhausted: bool


class CursorManager:
    """Process-wide registry of server-side cursors.

    One :class:`CursorManager` is instantiated by the server lifespan
    and stored in :class:`mcpg.context.AppContext`. Open / fetch /
    close tools route through it.
    """

    def __init__(
        self,
        database_url: str,
        *,
        ttl_seconds: float = DEFAULT_CURSOR_TTL_SECONDS,
        max_open: int = DEFAULT_MAX_OPEN_CURSORS,
    ) -> None:
        self._database_url = database_url
        self._ttl_seconds = ttl_seconds
        self._max_open = max_open
        self._cursors: dict[str, _ActiveCursor] = {}
        self._lock = asyncio.Lock()

    @property
    def ttl_seconds(self) -> float:
        return self._ttl_seconds

    async def open(self, driver: SqlDriver, sql: str) -> CursorInfo:
        """Validate ``sql``, allocate a dedicated connection, DECLARE the cursor."""
        # SafeSqlDriver._validate parses and checks against the allowlist
        # without executing — once the SQL is approved we issue the
        # DECLARE on our own dedicated connection.
        try:
            SafeSqlDriver(sql_driver=driver)._validate(sql)
        except Exception as exc:
            raise CursorError(f"query rejected: {exc}") from exc

        await self._sweep_expired()
        async with self._lock:
            if len(self._cursors) >= self._max_open:
                raise CursorError(
                    f"too many open cursors ({len(self._cursors)} / {self._max_open}); close one before opening another"
                )
            cursor_id = self._new_cursor_id()

        # Open a dedicated connection — this stays open for the cursor's
        # lifetime. Failing here propagates as a CursorError so the
        # caller sees a useful message instead of a psycopg traceback.
        try:
            conn = await psycopg.AsyncConnection.connect(self._database_url)
        except Exception as exc:
            raise CursorError(f"could not open cursor connection: {exc}") from exc

        try:
            async with conn.cursor() as cur:
                # READ ONLY transaction — defence in depth even though
                # the SQL went through the safety allowlist.
                await cur.execute("BEGIN TRANSACTION READ ONLY")
                # Identifier is generated by us — random hex, safe to
                # inline. The user's SQL is the cursor's query and is
                # already validated.
                await cur.execute(f'DECLARE "{cursor_id}" NO SCROLL CURSOR FOR {sql}')
        except Exception as exc:
            await conn.close()
            raise CursorError(f"DECLARE CURSOR failed: {exc}") from exc

        active = _ActiveCursor(cursor_id=cursor_id, sql=sql, connection=conn)
        async with self._lock:
            self._cursors[cursor_id] = active
        return self._public_info(active)

    async def fetch(self, cursor_id: str, batch_size: int = DEFAULT_FETCH_BATCH) -> FetchResult:
        if batch_size < 1:
            raise CursorError("batch_size must be at least 1")
        if batch_size > HARD_FETCH_BATCH:
            raise CursorError(f"batch_size too large; hard cap is {HARD_FETCH_BATCH}")

        await self._sweep_expired()
        async with self._lock:
            active = self._cursors.get(cursor_id)
        if active is None or active.closed:
            raise CursorError(f"unknown cursor_id: {cursor_id!r}")

        # Serialise concurrent fetch / close on the same cursor. psycopg's
        # AsyncConnection isn't safe for concurrent task access; without
        # this lock two simultaneous fetches on the same cursor_id would
        # corrupt the wire protocol.
        fetch_error: Exception | None = None
        rows: list[dict[str, Any]] = []
        async with active.use_lock:
            # Re-check after acquiring — a concurrent close may have run.
            if active.closed:
                raise CursorError(f"unknown cursor_id: {cursor_id!r}")
            try:
                async with active.connection.cursor(row_factory=dict_row) as cur:
                    await cur.execute(f'FETCH FORWARD {batch_size} FROM "{cursor_id}"')
                    fetched = await cur.fetchall()
                rows = [dict(row) for row in fetched]
            except Exception as exc:
                # On any failure, close the cursor so the connection isn't
                # left in a broken state. Defer the close call to outside
                # the lock so _close_internal can re-acquire it.
                fetch_error = exc

        if fetch_error is not None:
            await self._close_internal(cursor_id)
            raise CursorError(f"FETCH failed; cursor closed: {fetch_error}") from fetch_error

        columns: list[str] = list(rows[0].keys()) if rows else []
        exhausted = len(rows) < batch_size
        active.last_touched = time.monotonic()
        active.rows_returned += len(rows)

        return FetchResult(
            cursor_id=cursor_id,
            columns=columns,
            rows=rows,
            row_count=len(rows),
            exhausted=exhausted,
        )

    async def close(self, cursor_id: str) -> bool:
        """Close a cursor and release its dedicated connection.

        Returns ``True`` if the cursor was open, ``False`` if it
        wasn't found (already closed / expired / never existed) —
        callers don't need to special-case the not-found case.
        """
        return await self._close_internal(cursor_id)

    async def list_open(self) -> list[CursorInfo]:
        """Return one :class:`CursorInfo` per currently-open cursor."""
        await self._sweep_expired()
        async with self._lock:
            return [self._public_info(c) for c in self._cursors.values() if not c.closed]

    async def close_all(self) -> None:
        """Close every cursor — called from the server lifespan exit."""
        async with self._lock:
            ids = list(self._cursors.keys())
        for cid in ids:
            await self._close_internal(cid)

    # --- internals ---------------------------------------------------

    def _new_cursor_id(self) -> str:
        # `mcpg_<8 hex>` — short, identifier-safe, collision-unlikely.
        return f"mcpg_{secrets.token_hex(6)}"

    def _public_info(self, active: _ActiveCursor) -> CursorInfo:
        return CursorInfo(
            cursor_id=active.cursor_id,
            sql=active.sql,
            rows_returned=active.rows_returned,
            age_seconds=time.monotonic() - active.last_touched,
            ttl_seconds=self._ttl_seconds,
        )

    async def _close_internal(self, cursor_id: str) -> bool:
        async with self._lock:
            active = self._cursors.pop(cursor_id, None)
        if active is None or active.closed:
            return False
        # Hold the per-cursor lock so a racing fetch can't run CLOSE
        # concurrently with FETCH on the same psycopg connection.
        async with active.use_lock:
            if active.closed:
                return False
            active.closed = True
            try:
                async with active.connection.cursor() as cur:
                    await cur.execute(f'CLOSE "{cursor_id}"')
                    await cur.execute("ROLLBACK")
            except Exception:
                # Connection may already be in a broken state — swallow,
                # the close-callable below cleans up anyway.
                pass
        try:
            await active.connection.close()
        except Exception as exc:
            logger.warning("Error closing cursor %s connection: %s", cursor_id, exc)
        return True

    async def _sweep_expired(self) -> None:
        now = time.monotonic()
        async with self._lock:
            expired = [cid for cid, active in self._cursors.items() if now - active.last_touched > self._ttl_seconds]
        for cid in expired:
            await self._close_internal(cid)

    async def __aenter__(self) -> CursorManager:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.close_all()


async def iter_cursor(
    manager: CursorManager, cursor_id: str, batch_size: int = DEFAULT_FETCH_BATCH
) -> AsyncIterator[dict[str, Any]]:
    """Convenience iterator: yield rows from a cursor until exhausted.

    Doesn't close the cursor on exit — callers retain control. Useful
    in tests and in tools that want to drain a cursor in one pass.
    """
    while True:
        result = await manager.fetch(cursor_id, batch_size=batch_size)
        for row in result.rows:
            yield row
        if result.exhausted:
            return
