"""Migration-script ingestion — list pending Alembic / Flyway / Liquibase migrations.

This module pairs the on-disk migration scripts (the source of truth
for what *should* run) with the database's history table (the source
of truth for what *has* run) and reports the delta. It does **not**
execute migrations; that's the existing :mod:`mcpg.migrations`
``prepare_migration`` / ``apply_migration`` surface. Think of this as
the "what's pending" half of the migration ecosystem story —
:mod:`mcpg.migration_history` reads the history table, this reads the
filesystem, and the cross-reference is what surfaces to the agent.

Filesystem access is gated. By default the tool refuses every path:
operators opt in by setting ``MCPG_MIGRATION_SCRIPTS_ROOTS`` to a
colon-separated list of absolute directory prefixes. A requested
``scripts_dir`` is resolved (symlinks dereferenced) and must live
under one of those prefixes. ``..`` traversal is rejected at the
resolution step.

Supported frameworks:

- ``flyway`` — versioned SQL files named ``V<version>__<desc>.sql``.
  Identifier = the ``<version>`` component; cross-referenced against
  ``flyway_schema_history.version``. Repeatable migrations
  (``R__...``) and undo migrations (``U<version>__...``) are
  recognised but treated as out-of-scope for the "pending" notion.
- ``alembic`` — Python files named ``<revision_id>_<slug>.py``.
  Identifier = ``<revision_id>`` (the prefix before the first
  underscore). Cross-referenced against ``alembic_version.version_num``.
  Alembic stores migrations as Python (not SQL) so this tool only
  reports the pending list; the operator drives ``alembic upgrade``
  for execution.
- ``liquibase`` — SQL changelog files. Identifier = the filename
  without the ``.sql`` suffix; cross-referenced against
  ``databasechangelog.id``. XML / YAML changelogs are intentionally
  out of scope for this v1.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from mcpg._vendor.sql import SqlDriver

_FRAMEWORKS = frozenset({"alembic", "flyway", "liquibase"})

# Filename → identifier extractors. The pattern's first capture group
# is the identifier; non-matching filenames are skipped (so README.md
# / __init__.py / env.py don't leak into the report).
_FLYWAY_VERSIONED = re.compile(r"^V(\d+(?:[._]\d+)*)__.+\.sql$")
# Alembic revision IDs are alphanumeric (the autogenerated ones are
# 12 hex chars but users can choose anything alembic accepts).
_ALEMBIC_REVISION = re.compile(r"^([a-zA-Z0-9]+)_.+\.py$")
# Liquibase changeset ids are arbitrary strings the user supplies in
# the changelog — for filename-based tracking we use the stem.
_LIQUIBASE_SQL = re.compile(r"^(.+)\.sql$", re.IGNORECASE)

# Map of (framework, history table candidates). One framework can have
# its history table in any schema, so we list table names and let the
# caller hand us the schema (or scan the catalog when ``history_schema``
# is ``None``). Table existence is checked up-front; when none of these
# tables is present we report ``available=False`` so the tool's caller
# can distinguish "nothing applied yet" from "no history infrastructure".
_HISTORY_TABLES: dict[str, tuple[str, ...]] = {
    "flyway": ("flyway_schema_history",),
    "alembic": ("alembic_version",),
    "liquibase": ("databasechangelog",),
}

# Cap on how much of a script's text we sniff for the first non-blank
# comment line. Keeps the structured result small while still giving
# the agent a hint of what the migration does.
_PREVIEW_BYTES = 4096
_FIRST_COMMENT_CAP = 200


class MigrationIngestionError(Exception):
    """Raised when a migration-ingestion request is rejected."""


@dataclass(frozen=True, slots=True)
class PendingMigration:
    """One on-disk script that hasn't been applied yet.

    ``first_comment`` is the first non-blank line of the file when it
    looks like a SQL or Python comment (``--`` / ``/*`` / ``#``).
    It's a hint for the agent — useful for "what does V0042 do?"
    without having to read the whole file.
    """

    identifier: str
    filename: str
    size_bytes: int
    first_comment: str | None = None


@dataclass(frozen=True, slots=True)
class PendingMigrationsReport:
    """Outcome of a :func:`list_pending_migrations` call.

    ``available`` is ``False`` when the framework's history table is
    missing — that's distinct from ``pending_count == 0`` ("everything
    applied"). ``applied`` carries just the identifiers; the full
    history rows live in :func:`mcpg.migration_history.read_migration_history`.
    """

    available: bool
    framework: str
    scripts_dir: str
    history_table: str | None
    applied_count: int
    pending_count: int
    pending: list[PendingMigration] = field(default_factory=list)
    applied: list[str] = field(default_factory=list)
    notes: str = ""


def _normalize_roots(roots: tuple[str, ...]) -> list[Path]:
    """Resolve operator-configured roots to canonical absolute paths.

    Roots that aren't absolute or don't exist on disk are dropped
    silently — the tool's contract is "must live under one of these"
    so a broken root is just an unavailable prefix, not a hard error
    at config time.
    """
    out: list[Path] = []
    for root in roots:
        candidate = Path(root)
        if not candidate.is_absolute():
            continue
        try:
            resolved = candidate.resolve(strict=True)
        except (FileNotFoundError, OSError):
            continue
        if resolved.is_dir():
            out.append(resolved)
    return out


def _resolve_under_root(scripts_dir: str, allowed_roots: tuple[str, ...]) -> Path:
    """Resolve ``scripts_dir`` and confirm it lives under an allowed root.

    Symlinks are followed at resolve time so a symlink pointing
    outside the allowed root can't escape the sandbox. ``..`` is
    accepted in the input string but won't help: ``resolve(strict=True)``
    canonicalises it before the prefix check.
    """
    if not scripts_dir:
        raise MigrationIngestionError("scripts_dir is required")
    if not Path(scripts_dir).is_absolute():
        raise MigrationIngestionError(f"scripts_dir must be an absolute path (got {scripts_dir!r})")
    roots = _normalize_roots(allowed_roots)
    if not roots:
        raise MigrationIngestionError(
            "no migration script roots configured; set MCPG_MIGRATION_SCRIPTS_ROOTS to "
            "a colon-separated list of absolute directories the tool may read from"
        )
    try:
        target = Path(scripts_dir).resolve(strict=True)
    except FileNotFoundError as exc:
        raise MigrationIngestionError(f"scripts_dir does not exist: {scripts_dir}") from exc
    except OSError as exc:
        raise MigrationIngestionError(f"scripts_dir is not accessible: {scripts_dir}") from exc
    if not target.is_dir():
        raise MigrationIngestionError(f"scripts_dir is not a directory: {scripts_dir}")
    for root in roots:
        try:
            target.relative_to(root)
        except ValueError:
            continue
        return target
    raise MigrationIngestionError(
        f"scripts_dir {scripts_dir!r} is outside MCPG_MIGRATION_SCRIPTS_ROOTS — "
        "add its parent to the allowlist to permit access"
    )


def _first_comment_line(text: str) -> str | None:
    """Return the first SQL/Python comment line, trimmed and capped."""
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith(("--", "/*", "*", "#")):
            return stripped[:_FIRST_COMMENT_CAP]
        # First non-blank, non-comment line ends the sniff — we don't
        # want to misreport a code-style identifier as a description.
        return None
    return None


def _read_preview(path: Path) -> str:
    """Read the first ``_PREVIEW_BYTES`` of ``path`` as UTF-8 (errors=replace)."""
    try:
        with path.open("rb") as handle:
            blob = handle.read(_PREVIEW_BYTES)
    except OSError:
        return ""
    return blob.decode("utf-8", errors="replace")


def _extract_identifier(framework: str, filename: str) -> str | None:
    """Pull the framework-specific identifier out of a script filename."""
    if framework == "flyway":
        match = _FLYWAY_VERSIONED.match(filename)
        # Normalise "1_2" → "1.2" — Flyway accepts both as the same version.
        return match.group(1).replace("_", ".") if match else None
    if framework == "alembic":
        # Skip alembic's reserved files explicitly so they don't slip
        # through the regex (env.py / __init__.py both fail the
        # pattern but being explicit guards against future changes).
        if filename in {"env.py", "__init__.py"}:
            return None
        match = _ALEMBIC_REVISION.match(filename)
        return match.group(1) if match else None
    if framework == "liquibase":
        match = _LIQUIBASE_SQL.match(filename)
        return match.group(1) if match else None
    return None


async def _detect_history_table(
    driver: SqlDriver, framework: str, history_schema: str | None
) -> tuple[str, str] | None:
    """Locate the framework's history table; return ``(schema, table)`` or ``None``."""
    candidate_tables = _HISTORY_TABLES[framework]
    query = (
        "SELECT table_schema, table_name FROM information_schema.tables "
        "WHERE table_name = ANY(%s) "
        "AND table_schema NOT IN ('pg_catalog', 'information_schema')"
    )
    params: list[object] = [list(candidate_tables)]
    if history_schema:
        query += " AND table_schema = %s"
        params.append(history_schema)
    query += " ORDER BY table_schema, table_name LIMIT 1"
    rows = await driver.execute_query(query, params=params, force_readonly=True)
    if not rows:
        return None
    cell = rows[0].cells
    return str(cell["table_schema"]), str(cell["table_name"])


async def _read_applied_identifiers(driver: SqlDriver, framework: str, schema: str, table: str) -> list[str]:
    """Read the identifier column from the framework's history table."""
    quoted_schema = f'"{schema.replace(chr(34), chr(34) * 2)}"'
    quoted_table = f'"{table.replace(chr(34), chr(34) * 2)}"'
    relation = f"{quoted_schema}.{quoted_table}"
    if framework == "flyway":
        # ``success = true`` filters out failed attempts; ``version``
        # is NULL for repeatable migrations (R__), which we don't
        # surface in the pending list either.
        rows = await driver.execute_query(
            f"SELECT version::text AS identifier FROM {relation} WHERE success = true AND version IS NOT NULL",
            force_readonly=True,
        )
    elif framework == "alembic":
        rows = await driver.execute_query(
            f"SELECT version_num::text AS identifier FROM {relation}",
            force_readonly=True,
        )
    elif framework == "liquibase":
        rows = await driver.execute_query(
            f"SELECT id::text AS identifier FROM {relation}",
            force_readonly=True,
        )
    else:
        return []
    return [str(row.cells["identifier"]) for row in rows or []]


def _scan_scripts_dir(target: Path, framework: str) -> list[tuple[str, str, int, str | None]]:
    """Return ``(identifier, filename, size, first_comment)`` per recognised script.

    Walks ``target`` one level deep — recursing into subdirectories
    would silently double-count scripts in nested layouts (e.g.
    Alembic's ``versions/`` subdir). Operators point the tool at the
    leaf directory.
    """
    out: list[tuple[str, str, int, str | None]] = []
    try:
        entries = sorted(os.scandir(target), key=lambda e: e.name)
    except OSError:
        return out
    for entry in entries:
        if entry.name.startswith("."):
            continue
        # Use is_file with follow_symlinks=True so symlinks inside the
        # allowed root resolve normally. The earlier strict-resolve on
        # scripts_dir already guards the directory boundary.
        try:
            if not entry.is_file(follow_symlinks=True):
                continue
        except OSError:
            continue
        identifier = _extract_identifier(framework, entry.name)
        if identifier is None:
            continue
        try:
            stat = entry.stat()
            size = int(stat.st_size)
        except OSError:
            continue
        first_comment = _first_comment_line(_read_preview(Path(entry.path)))
        out.append((identifier, entry.name, size, first_comment))
    return out


async def list_pending_migrations(
    driver: SqlDriver,
    framework: str,
    scripts_dir: str,
    history_schema: str | None = None,
    *,
    allowed_roots: tuple[str, ...] = (),
) -> PendingMigrationsReport:
    """List migration scripts on disk that haven't been applied yet.

    Walks ``scripts_dir`` (one level deep), extracts each script's
    identifier per the framework's filename convention, cross-references
    against the framework's history table, and returns the pending set
    alongside the applied identifiers.

    ``available=False`` distinctly from ``pending_count == 0`` covers
    the "no history table at all" case — useful for greenfield
    databases where every on-disk script is "pending" but the database
    has no opinion yet.

    Args:
        framework: One of ``alembic``, ``flyway``, ``liquibase``.
        scripts_dir: Absolute directory path containing the migration
            scripts. Must live under one of ``allowed_roots``.
        history_schema: Optional schema name to constrain the history-
            table lookup. ``None`` searches every non-system schema.
        allowed_roots: Tuple of absolute directories the tool may read
            from (typically wired up from ``MCPG_MIGRATION_SCRIPTS_ROOTS``).

    Raises:
        MigrationIngestionError: On an unknown framework, an empty /
            malformed ``scripts_dir``, a path outside ``allowed_roots``,
            or a path that doesn't exist / isn't a directory.
    """
    if framework not in _FRAMEWORKS:
        raise MigrationIngestionError(f"unknown framework {framework!r}; expected one of {sorted(_FRAMEWORKS)}")
    target = _resolve_under_root(scripts_dir, allowed_roots)

    history = await _detect_history_table(driver, framework, history_schema)
    if history is None:
        # Greenfield path: still report the scripts on disk so the
        # caller can plan a from-scratch apply.
        scripts = _scan_scripts_dir(target, framework)
        pending = [
            PendingMigration(identifier=ident, filename=name, size_bytes=size, first_comment=comment)
            for ident, name, size, comment in scripts
        ]
        return PendingMigrationsReport(
            available=False,
            framework=framework,
            scripts_dir=str(target),
            history_table=None,
            applied_count=0,
            pending_count=len(pending),
            pending=pending,
            applied=[],
            notes=(
                f"No {framework} history table found in this database — every script in "
                f"{target} is reported as pending."
            ),
        )

    history_schema_name, history_table_name = history
    applied = await _read_applied_identifiers(driver, framework, history_schema_name, history_table_name)
    applied_set = set(applied)

    scripts = _scan_scripts_dir(target, framework)
    pending = [
        PendingMigration(identifier=ident, filename=name, size_bytes=size, first_comment=comment)
        for ident, name, size, comment in scripts
        if ident not in applied_set
    ]
    history_label = f"{history_schema_name}.{history_table_name}"
    notes = (
        f"Scanned {len(scripts)} {framework} script(s) in {target}; "
        f"history table {history_label} reports {len(applied)} applied — "
        f"{len(pending)} pending."
    )
    return PendingMigrationsReport(
        available=True,
        framework=framework,
        scripts_dir=str(target),
        history_table=history_label,
        applied_count=len(applied),
        pending_count=len(pending),
        pending=pending,
        applied=sorted(applied),
        notes=notes,
    )
