FROM postgres:16-bookworm@sha256:92620daddcd947f8d5ab5ba66e848702fe443d87fed30c4cea8e389fd78dfc55

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    git \
    perl \
    postgresql-server-dev-16 \
    libipc-run-perl \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
